name : Docker-CI

trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: 'agung1ds/devops-assignment:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        command: 'build'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
        arguments: '--target production'
     
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'dockerhub'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- stage: Package
  displayName: Helm Package
  jobs:  
  - job: Installer
    displayName: Helm Installer
    steps:
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true

    - task: HelmDeploy@0
      displayName: Helm Packages
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'aks'
        azureResourceGroup: 'devops'
        kubernetesCluster: 'testing'
        useClusterAdmin: true
        command: 'package'
        chartPath: 'devops'
        chartVersion: '$(Build.BuildId)'
        destination: $(Build.ArtifactStagingDirectory)

    - task: PublishPipelineArtifact@0
      displayName: Helm Deploy
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'gotest'
        publishLocation: 'pipeline'
    
    - task: HelmDeploy@0
      displayName: Helm Upgrade
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'aks'
        azureResourceGroup: 'devops'
        kubernetesCluster: 'testing'
        useClusterAdmin: true
        namespace: 'default'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '$(Build.ArtifactStagingDirectory)/devops-$(Build.BuildId).tgz'
        chartVersion: '$(Build.BuildId)'
        releaseName: 'gotest'
        arguments: '--set image.tag=$(Build.BuildId)'


    




    